# Generated by Django 3.2.6 on 2021-08-24 02:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_name",
                    models.CharField(max_length=255, verbose_name="Room name"),
                ),
                (
                    "turn",
                    models.CharField(
                        choices=[("x", "Player 1"), ("o", "Player 2")],
                        max_length=255,
                        verbose_name="Game turn",
                    ),
                ),
                (
                    "board",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(
                                blank=True, max_length=10, null=True
                            ),
                            size=6,
                        ),
                        blank=True,
                        size=6,
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Winner"
                    ),
                ),
            ],
        ),
    ]
