# Generated by Django 3.2.6 on 2021-09-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_game_number_of_movements"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="id_player_one",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Id channel player 1",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="id_player_two",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Id channel player 1",
            ),
        ),
    ]
