# Generated by Django 3.2.6 on 2021-08-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_alter_game_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="turn",
            field=models.CharField(
                choices=[("1", "Player 1"), ("2", "Player 2")],
                default=1,
                max_length=255,
                verbose_name="Game turn",
            ),
            preserve_default=False,
        ),
    ]
