# Generated by Django 3.2.6 on 2021-08-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_game_turn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="turn",
            field=models.CharField(
                choices=[("x", "Player 1"), ("o", "Player 2")],
                max_length=255,
                verbose_name="Game turn",
            ),
        ),
    ]
