# Generated by Django 3.2.6 on 2021-08-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0005_alter_game_turn"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Winner"
            ),
        ),
    ]
